echo "<?php\n";
echo "\n";
echo "<!DOCTYPE HTML>\n";
echo "<html> <!-- class=\"loading\"-->\n";
echo "<head>\n";
echo "    <title>Curriculum Vittae :: Daniel Scheidemantel Camargo</title>\n";
echo "    <meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\"/>\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
echo "    <meta name=\"description\" content=\"Curriculum Daniel Scheidemantel Camargo\"/>\n";
echo "    <meta name=\"keywords\" content=\"Curriculum; Daniel; Scheidemantel; Camargo\"/>\n";
echo "    <meta name=\"referrer\" content=\"origin\">\n";
echo "\n";
echo "    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"ico/apple-icon-57x57.png\">\n";
echo "    <link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"ico/apple-icon-60x60.png\">\n";
echo "    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"ico/apple-icon-72x72.png\">\n";
echo "    <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"ico/apple-icon-76x76.png\">\n";
echo "    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"ico/apple-icon-114x114.png\">\n";
echo "    <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"ico/apple-icon-120x120.png\">\n";
echo "    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"ico/apple-icon-144x144.png\">\n";
echo "    <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"ico/apple-icon-152x152.png\">\n";
echo "    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"ico/apple-icon-180x180.png\">\n";
echo "    <!--[if IE]><link rel=\"shortcut icon\" href=\"ico/favicon.ico\"><![endif]-->\n";
echo "    <link rel=\"icon\" type=\"image/png\" sizes=\"192x192\"  href=\"ico/android-icon-192x192.png\">\n";
echo "    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"ico/favicon-32x32.png\">\n";
echo "    <link rel=\"icon\" type=\"image/png\" sizes=\"96x96\" href=\"ico/favicon-96x96.png\">\n";
echo "    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"ico/favicon-16x16.png\">\n";
echo "    <link rel=\"manifest\" href=\"/manifest.json\">\n";
echo "    <meta name=\"msapplication-TileColor\" content=\"#ffffff\">\n";
echo "    <meta name=\"msapplication-TileImage\" content=\"ico/ms-icon-144x144.png\">\n";
echo "    <meta name=\"theme-color\" content=\"#ffffff\">\n";
echo "\n";
echo "    <meta name=\"referrer\" content=\"origin\">\n";
echo "    <script src=\"js/jquery.min.js\"></script>\n";
echo "    <script src=\"js/jquery.scrolly.min.js\"></script>\n";
echo "    <script src=\"js/jquery.scrollzer.min.js\"></script>\n";
echo "    <script src=\"js/skel.min.js\"></script>\n";
echo "    <script src=\"js/skel-layers.min.js\"></script>\n";
echo "    <script src=\"js/init.js\"></script>\n";
echo "    <script src=\"//code.jquery.com/jquery-1.10.2.js\"></script>\n";
echo "    <script>\n";
echo "        $(function(){$(\"#footer\").load(\"footer.html\");});\n";
echo "    </script>\n";
echo "    <noscript>\n";
echo "        <link rel=\"stylesheet\" href=\"css/skel.css\"/>\n";
echo "        <link rel=\"stylesheet\" href=\"css/style.css\"/>\n";
echo "        <link rel=\"stylesheet\" href=\"css/style-wide.css\"/>\n";
echo "    </noscript>\n";
echo "</head>\n";
echo "<body>\n";
echo "\n";
echo "<!-- Header -->\n";
echo "<div id=\"header\" class=\"skel-layers-fixed entry-header\">\n";
echo "\n";
echo "    <div id=\"loader-wrapper\">\n";
echo "        <div id=\"loader\"></div>\n";
echo "        <div class=\"loader-section section-left\"></div>\n";
echo "        <div class=\"loader-section section-right\"></div>\n";
echo "    </div>\n";
echo "\n";
echo "    <div class=\"top\">\n";
echo "        <header>\n";
echo "            <h1 class=\"entry-title\">Curriculum Vittae</h1>\n";
echo "        </header>\n";
echo "        <!-- Logo -->\n";
echo "        <div id=\"logo\">\n";
echo "            <a href=\"#top\" class=\"image avatar48\"><img src=\"images/me.jpg\"/></a><br>\n";
echo "        </div>\n";
echo "        <!-- Nav -->\n";
echo "        <nav id=\"nav\">\n";
echo "            <ul>\n";
echo "                <li>\n";
echo "                    <a href=\"#top\" id=\"top-link\" class=\"skel-layers-ignoreHref\"><span class=\"icon fa-address-card\">Personal info</span></a>\n";
echo "                </li>\n";
echo "                <li>\n";
echo "                    <a href=\"#summary\" id=\"summary-link\" class=\"skel-layers-ignoreHref\"><span class=\"icon fa-list-alt\">Summary</span></a>\n";
echo "                </li>\n";
echo "                <li>\n";
echo "                    <a href=\"#experience\" id=\"experience-link\" class=\"skel-layers-ignoreHref\"><span class=\"icon fa-briefcase\">Experience</span></a>\n";
echo "                </li>\n";
echo "                <li>\n";
echo "                    <a href=\"#education\" id=\"education-link\" class=\"skel-layers-ignoreHref\"><span class=\"icon fa-graduation-cap\">Education</span></a>\n";
echo "                </li>\n";
echo "                <li>\n";
echo "                    <a href=\"#skills\" id=\"skills-link\" class=\"skel-layers-ignoreHref\"><span class=\"icon fa-puzzle-piece\">Skills</span></a>\n";
echo "                </li>\n";
echo "                <!--li>\n";
echo "                    <a href=\"#portfolio\" id=\"portfolio-link\" class=\"skel-layers-ignoreHref\"><span class=\"icon fa-th\">Portfolio</span></a>\n";
echo "                </li-->\n";
echo "                <li>\n";
echo "                    <a href=\"#contact\" id=\"contact-link\" class=\"skel-layers-ignoreHref\"><span class=\"icon fa-envelope\">Contact</span></a>\n";
echo "                </li>\n";
echo "                <li>\n";
echo "                    <a href=\"index.php\" id=\"return\" class=\"skel-layers-ignoreHref\"><span class=\"icon fa-home\">Back to home</span></a>\n";
echo "                </li>\n";
echo "            </ul>\n";
echo "        </nav>\n";
echo "    </div>\n";
echo "\n";
echo "</div>\n";
echo "\n";
echo "<!-- Main -->\n";
echo "<div id=\"main\">\n";
echo "\n";
echo "    <!-- Personal -->\n";
echo "    <section id=\"top\" class=\"two cover\">\n";
echo "\n";
echo "        <div class=\"container\">\n";
echo "            <header>\n";
echo "                <h3>Personal info</h3>\n";
echo "\n";
echo "                <p class=\"icon fa-user\"> Daniel Scheidemantel Camargo</p>\n";
echo "                <p class=\"icon fa-map-marker\"> General Camara Street, 435, Bom Retiro, Joinville/SC – Brazil</p>\n";
echo "                <p class=\"icon fa-phone\" > +55 (47) 99967-5469 / 3227-5121</p>\n";
echo "                <p class=\"icon fa-envelope\"> daniel.supervisao <strong class=\"icon fa-at\" style=\"font-size:14px\"></strong> gmail.com</p>\n";
echo "                <p class=\"icon fa-male\"> Sex: Male,\n";
echo "                    <i class=\"icon fa-birthday-cake\"></i> Birth: 1986-Jan,\n";
echo "                    <i class=\"icon fa-venus-mars\"></i> Married </p>\n";
echo "                <br>\n";
echo "                External info:\n";
echo "                <p class=\"icon fa-university\"> <a href=\"http://lattes.cnpq.br/3806326022567893\"> Lattes Curriculum</a> (Scientific)</p>\n";
echo "                <p class=\"icon fa-linkedin\"> <a href=\"https://www.linkedin.com/in/daniel13\"> Linkedin </a> (Social Network) </p>\n";
echo "            </header>\n";
echo "        </div>\n";
echo "    </section>\n";
echo "\n";
echo "    <!-- summary -->\n";
echo "    <section id=\"summary\" class=\"three\">\n";
echo "        <div class=\"container\">\n";
echo "\n";
echo "            <header>\n";
echo "                <h2>Summary</h2>\n";
echo "            </header>\n";
echo "\n";
echo "\n";
echo "            <p> Master Degree (stricto sensu) in Applied Computing in Santa Catarina State University (UDESC), 2018.\n";
echo "            <p> Graduated in Computer Science Bachelor also in UDESC (2016).\n";
echo "            <p> Knowledge in programming languages, like C/C++, Java, Python, Shell Script, for GNU/Linux, MS Windows, Web-development and microcontrollers (ATMEL).\n";
echo "            <p> Open source hardware and software like Arduino and ARM plataforms.\n";
echo "            <p> Participation through lectures and courses in events like Latinoware, FISL, FLISOL, etc.\n";
echo "            <p> Scientifics publications in ERAD, IEEE/CLEI/SCCC, RITA, etc. (Please see the <a target=\"_blank\" href=\"http://lattes.cnpq.br/3806326022567893\" >list</a>).\n";
echo "            <p> Topics of interest: Internet of Things (IoT), Cloud Computing, Green IT and Artificial Intelligence.\n";
echo "            <p> Currently has two research projects at <a target=\"_blank\" href=\"http://labp2d.udesc.br\" >LabP2D</a>, at UDESC.\n";
echo "            <p> 1º: \"GreenHop: Data Center Sensing and Automation\", 2º: \"CHAVE: Consolidation and High Availability on Virtual Environments\".\n";
echo "            <p> Professional experience on startup <a target=\"_blank\" href=\"http://www.reciclacomigo.com.br\" >Recicla Comigo</a>, winner of the \"Sinapse Inovação\" Award in 2016\n";
echo "            with the proposal of a reverse logistics machine for recycle cans and bottles, being responsible for the development of the machine's computational hardware, the website and the virtual infrastructure hosted on Amazon Web Services (AWS).\n";
echo "\n";
echo "        </div>\n";
echo "    </section>\n";
echo "\n";
echo "    <!-- experience -->\n";
echo "    <section id=\"experience\" class=\"two\">\n";
echo "        <div class=\"container\">\n";
echo "\n";
echo "            <header>\n";
echo "                <h2>Professional Experience</h2>\n";
echo "            </header>\n";
echo "\n";
echo "            <p>Comigo Ltda. - Cloud Architect, Infrastructure management </p>\n";
echo "            <p>2016-oct, till today</p>\n";
echo "\n";
echo "            <p>Computer Science Dept. UDESC - Teacher Treinee</p>\n";
echo "            <p>2017-aug, 2017-dec</p>\n";
echo "\n";
echo "            <p>Computer Science Dept. UDESC - Research Treinee</p>\n";
echo "            <p>2016-aug, till today</p>\n";
echo "\n";
echo "        </div>\n";
echo "    </section>\n";
echo "\n";
echo "    <!-- education -->\n";
echo "    <section id=\"education\" class=\"three\">\n";
echo "        <div class=\"container\">\n";
echo "\n";
echo "            <header>\n";
echo "                <h2>Education</h2>\n";
echo "            </header>\n";
echo "\n";
echo "            <p> Master degree in computer networks and systems, with focus in cloud computing, energy efficiency and critical systems analysis.\n";
echo "\n";
echo "                <a target=\"_blank\" href=\"http://www.cct.udesc.br\" class=\"icon fa-university\"> UDESC - Joinville/SC</a></p>\n";
echo "        </div>\n";
echo "    </section>\n";
echo "\n";
echo "    <!-- skills -->\n";
echo "    <section id=\"skills\" class=\"two\">\n";
echo "        <div class=\"container\">\n";
echo "\n";
echo "            <header>\n";
echo "                <h2>Skills</h2>\n";
echo "            </header>\n";
echo "\n";
echo "            <p>\n";
echo "                <strong>\n";
echo "                    <a target=\"_blank\" href=\"http://www.cct.udesc.br\" class=\"icon fa-university\"> UDESC -\n";
echo "                        Joinville/SC</a><br>\n";
echo "            <p> texto</p>\n";
echo "        </div>\n";
echo "    </section>\n";
echo "    <!-- Contact -->\n";
echo "    <section id=\"contact\" class=\"four\">\n";
echo "        <div class=\"container\">\n";
echo "            <header>\n";
echo "                <h2>Contact</h2>\n";
echo "            </header>\n";
echo "            <form method=\"POST\" action=\"https://formspree.io/daniel.camargo@hotmail.com\" >\n";
echo "                <div class=\"row half\">\n";
echo "                    <div class=\"6u\"><input type=\"text\" name=\"name\" placeholder=\"Your name\"/></div>\n";
echo "                    <div class=\"6u\"><input type=\"email\" name=\"email\" placeholder=\"Your e-mail\"/></div>\n";
echo "                    <input type=\"hidden\" name=\"_subject\" value=\"From site: danielfloripa.io curriculum\"/>\n";
echo "                </div>\n";
echo "                <div class=\"row half\">\n";
echo "                    <div class=\"12u\">\n";
echo "                        <textarea name=\"message\" placeholder=\"Your message\">
echo "                        <input type=\"submit\" value=\"Send Message!\"/>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "                <input type=\"hidden\" name=\"_next\" value=\"thanks.php\" />\n";
echo "            </form>\n";
echo "        </div>\n";
echo "    </section>\n";
echo "\n";
echo "</div>\n";
echo "\n";
echo "<!-- Footer -->\n";
echo "<div id=\"footer\"> <!--#include file=\"footer.html\" --> </div>\n";
echo "\n";
echo "</body>\n";
echo "</html>\n";
echo "?>";
