<?php

echo "<!DOCTYPE HTML>\n";
echo "<html class=\"loading\">\n";
echo "<head>\n";
echo "    <title>Daniel S. Camargo</title>\n";
echo "    <meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\"/>\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
echo "    <meta name=\"description\" content=\"Curriculum Daniel Scheidemantel Camargo\"/>\n";
echo "    <meta name=\"keywords\" content=\"Curriculum; Daniel; Scheidemantel; Camargo\"/>\n";
echo "    <meta name=\"referrer\" content=\"origin\">\n";
echo "    \n";
echo "      <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"ico/apple-icon-57x57.png\">\n";
echo "      <link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"ico/apple-icon-60x60.png\">\n";
echo "      <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"ico/apple-icon-72x72.png\">\n";
echo "      <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"ico/apple-icon-76x76.png\">\n";
echo "      <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"ico/apple-icon-114x114.png\">\n";
echo "      <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"ico/apple-icon-120x120.png\">\n";
echo "      <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"ico/apple-icon-144x144.png\">\n";
echo "      <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"ico/apple-icon-152x152.png\">\n";
echo "      <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"ico/apple-icon-180x180.png\">\n";
echo "      <!--[if IE]><link rel=\"shortcut icon\" href=\"ico/favicon.ico\"><![endif]-->\n";
echo "      <link rel=\"icon\" type=\"image/png\" sizes=\"192x192\"  href=\"ico/android-icon-192x192.png\">\n";
echo "      <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"ico/favicon-32x32.png\">\n";
echo "      <link rel=\"icon\" type=\"image/png\" sizes=\"96x96\" href=\"ico/favicon-96x96.png\">\n";
echo "      <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"ico/favicon-16x16.png\">\n";
echo "      <link rel=\"manifest\" href=\"/manifest.json\">\n";
echo "      <meta name=\"msapplication-TileColor\" content=\"#ffffff\">\n";
echo "      <meta name=\"msapplication-TileImage\" content=\"ico/ms-icon-144x144.png\">\n";
echo "      <meta name=\"theme-color\" content=\"#ffffff\">\n";
echo "    \n";
echo "      <script src=\"js/jquery.min.js\"></script>\n";
echo "      <script src=\"js/jquery.scrolly.min.js\"></script>\n";
echo "      <script src=\"js/jquery.scrollzer.min.js\"></script>\n";
echo "      <script src=\"js/skel.min.js\"></script>\n";
echo "      <script src=\"js/skel-layers.min.js\"></script>\n";
echo "      <script src=\"js/init.js\"></script>\n";
echo "      <script src=\"\/\/code.jquery.com/jquery-1.10.2.js\"></script>\n";
echo "      <script>\n";
echo "          $(function(){$(\"#footer\").load(\"footer.html\");});\n";
echo "      </script>\n";
echo "    <noscript>\n";
echo "    <link rel=\"stylesheet\" href=\"css/skel.css\"/>\n";
echo "    <link rel=\"stylesheet\" href=\"css/style.css\"/>\n";
echo "    <link rel=\"stylesheet\" href=\"css/style-wide.css\"/>\n";
echo "    </noscript>\n";
echo "    <!--[if lte IE 9]><link rel=\"stylesheet\" href=\"css/ie/v9.css\"/><![endif]-->\n";
echo "    <!--[if lte IE 8]><link rel=\"stylesheet\" href=\"css/ie/v8.css\"/><![endif]-->\n";
echo "</head>\n";
echo "\n";
echo "<body>\n";
echo "<!-- Header -->\n";
echo "<div id=\"header\" class=\"skel-layers-fixed entry-header\">\n";
echo "  <div id=\"loader-wrapper\">\n";
echo "    <div id=\"loader\"></div>\n";
echo "    <div class=\"loader-section section-left\"></div>\n";
echo "    <div class=\"loader-section section-right\"></div>\n";
echo "  </div>\n";
echo "  <div class=\"top\">\n";
echo "    <header>\n";
echo "      <h1 class=\"entry-title\">Daniel S. Camargo</h1>\n";
echo "    </header>\n";
echo "    <!-- Logo -->\n";
echo "    <div id=\"logo\"> <a href=\"#top\" class=\"image avatar48\"><img src=\"images/me.jpg\"/></a> </div>\n";
echo "    <div class=\"title\">\n";
echo "      <p style=\"align:left\"> Research + Dev </p>\n";
echo "    </div>\n";
echo "    <!-- Nav -->\n";
echo "    <nav id=\"nav\">\n";
echo "      <ul>\n";
echo "        <li><a href=\"#top\" id=\"top-link\" class=\"skel-layers-ignoreHref\">\n";
echo "            <span class=\"icon fa-home\">Intro</span></a></li>\n";
echo "        <li><a href=\"curriculum.php\" id=\"curriculum-link\" class=\"skel-layers-ignoreHref\">\n";
echo "            <span class=\"icon fa-comment-alt\">Curriculum</span></a></li>\n";
echo "        <li><a href=\"#portfolio\" id=\"portfolio-link\" class=\"skel-layers-ignoreHref\">\n";
echo "            <span class=\"icon fa-th\">Portfolio</span></a> </li>\n";
echo "        <li><a href=\"#papers\" id=\"papers-link\" class=\"skel-layers-ignoreHref\">\n";
echo "            <span class=\"icon fa-newspaper\">Papers</span></a></li>\n";
echo "        <li><a href=\"#about\" id=\"about-link\" class=\"skel-layers-ignoreHref\">\n";
echo "        	<span class=\"icon fa-user\">About</span></a></li>\n";
echo "        <li><a href=\"#contact\" id=\"contact-link\" class=\"skel-layers-ignoreHref\">\n";
echo "            <span class=\"icon fa-envelope\">Contact</span></a></li>\n";
echo "          <li><a href=\"http:\/\/blog.dscar.ga\" id=\"blog-link\" class=\"skel-layers-ignoreHref\">\n";
echo "              <span class=\"icon fa-wordpress\">Blog</span></a></li>\n";
echo "      </ul>\n";
echo "    </nav>\n";
echo "  </div>\n";
echo "  <div class=\"bottom\">\n";
echo "\n";
echo "    <!-- Social Icons -->\n";
echo "    <ul class=\"icons\">\n";
echo "      <li>\n";
echo "          <a href=\"https:\/\/www.facebook.com/danielcamargo13\" class=\"icon fa-facebook\">\n";
echo "              <span class=\"label\"> Facebook </span></a>\n";
echo "      </li>\n";
echo "      <li>\n";
echo "          <a href=\"http:\/\/github.com/danielfloripa\" class=\"icon fa-github\">\n";
echo "              <span class=\"label\"> Github</span></a>\n";
echo "      </li>\n";
echo "      <li>\n";
echo "          <a href=\"https:\/\/www.linkedin.com/in/daniel13\" class=\"icon fa-linkedin \">\n";
echo "              <span class=\"label\"> Linkedin</span></a>\n";
echo "      </li>\n";
echo "      <li>\n";
echo "          <a href=\"http:\/\/api.whatsapp.com/send?phone=5547999675469&text=From%20site%20dscar.ga\" class=\"icon fa-whatsapp\"\n";
echo "             target=\"_blank\">\n";
echo "              <span class=\"label\"> Whatsapp</span></a>\n";
echo "      </li>\n";
echo "    </ul>\n";
echo "    <audio id=\"bgAudio\" autoplay=\"autoplay\" loop=\"loop\" preload=\"auto\" controls>\n";
echo "      <source src=\"musics/thunderrain.mp3\" type=\"audio/mpeg\">\n";
echo "    </audio>\n";
echo "    <script type=\"text/javascript\">\n";
echo "			window.onload = function () {\n";
echo "				var backgroundAudio = document.getElementById(\"bgAudio\");\n";
echo "				backgroundAudio.volume = 0.3;\n";
echo "				backgroundAudio.getAttribute.\n";
echo "				document.querySelector('audio').play();\n";
echo "			}\n";
echo "		</script>\n";
echo "  </div>\n";
echo "</div>\n";
echo "\n";
echo "<!-- Main -->\n";
echo "<div id=\"main\">\n";
echo "  <!-- Intro -->\n";
echo "  <section id=\"top\" class=\"video dark cover\">\n";
echo "    <video id=\"video_background\" preload=\"auto\" autoplay=\"autoplay\" loop=\"loop\" onended=\"this.play()\">\n";
echo "      <source src=\"https:\/\/danielfloripa.github.io/images/mboard.mp4\" type=\"video/mp4\">\n";
echo "    </video>\n";
echo "    <script type=\"text/javascript\">\n";
echo "            window.onload = function () {\n";
echo "                var backgroundVideo = document.getElementById(\"video_background\");\n";
echo "                document.querySelector('video').play();\n";
echo "            }\n";
echo "        </script>\n";
echo "    <div class=\"container\">\n";
echo "      <section id=\"page-hero\">\n";
echo "        <header>\n";
echo "          <h2 class=\"alt\">Are you going to hire me? <br>\n";
echo "            <a href=\"curriculum.php\">Curriculum Vittae</a></h2>\n";
echo "        </header>\n";
echo "        <footer> <a href=\"#portfolio\" class=\"scrolly\">\n";
echo "          <div class=\"subtle\">...Or see my portfolio below.</div>\n";
echo "          <svg xmlns=\"http:\/\/www.w3.org/2000/svg\" xmlns:xlink=\"http:\/\/www.w3.org/1999/xlink\" version=\"1.1\" id=\"arrow-down\" x=\"0px\" y=\"0px\" viewBox=\"0 0 50 50\" style=\"enable-background:new 0 0 50 50;\" xml:space=\"preserve\" class=\" iconic-injected-svg inject-me\">\n";
echo "            <path id=\"circle\" d=\"M0.2,27.4c-0.2-1.9-0.3-3.4,0-5.3c0.1-0.4,0.2-0.8,0.2-1.1C2.2,9.1,12.3,0.2,24.3,0c8.2-0.1,14.9,3,20.1,9.4  c3,3.8,4.6,8.2,5.3,12.9c0.1,2.5,0.1,2.5,0,4.7c-0.1,0.5-0.2,0.8-0.2,1.3C47.7,40.2,37.9,49.1,26,49.5c-10,0.3-17.5-4-22.7-12.6  C1.5,34,0.7,30.7,0.2,27.4z M2.3,24.7c-0.2,11.6,9.2,22.7,22.6,22.7c13.2,0,22.6-10.7,22.6-22.6c0-12-9.4-22.7-22.6-22.7  C11.4,2.1,2.2,13.3,2.3,24.7z\"></path>\n";
echo "            <path id=\"arrow\" class=\"st0\" d=\"M31.8,23.4c-0.2-0.3-0.6-0.3-0.9-0.1l-6,5l-6-5c-0.3-0.2-0.7-0.2-0.9,0.1c-0.2,0.3-0.2,0.7,0.1,0.9l6.5,5.4   c0.1,0.1,0.3,0.1,0.4,0.1c0.1,0,0.3,0,0.4-0.1l6.5-5.4C31.9,24,32,23.6,31.8,23.4z\"></path>\n";
echo "          </svg>\n";
echo "          </a> </footer>\n";
echo "      </section>\n";
echo "    </div>\n";
echo "  </section>\n";
echo "  <script type=\"text/javascript\">\n";
echo "        var sec1 = document.querySelector('#top');\n";
echo "        sec1.style.height = window.screen.height + 'px';\n";
echo "    </script>\n";
echo "\n";
echo "  <!-- Portfolio -->\n";
echo "  <section id=\"portfolio\" class=\"two\">\n";
echo "    <div class=\"container\">\n";
echo "      <header>\n";
echo "        <h2>Portfolio</h2>\n";
echo "      </header>\n";
echo "      <p><em>\"Scientia potentia est\"</em><br>\n";
echo "        Knowledge is power!</p>\n";
echo "      <div class=\"row\">\n";
echo "        <div class=\"4u\">\n";
echo "          <article class=\"item\">\n";
echo "          	<a href=\"https:\/\/github.com/danielfloripa/greenhop\" target=\"_blank\"  class=\"image fit\"><img src=\"images/greenhop.png\" alt=\"GreenHop\"/>\n";
echo "            <header>\n";
echo "              <h2>GreenHop</h2>\n";
echo "              <h3>Open source energy consumption and environmental monitoring for data center infrastructure</h3>\n";
echo "            </header>\n";
echo "            </a>\n";
echo "          </article>\n";
echo "        </div>\n";
echo "        <div class=\"4u\">\n";
echo "          <article class=\"item\">\n";
echo "          	<a href=\"https:\/\/github.com/DanielFloripa/MscProject\"  target=\"_blank\" class=\"image fit\"><img src=\"images/master3.jpg\" alt=\"Master\"/>\n";
echo "            <header>\n";
echo "              <h2>CHAVE Project</h2>\n";
echo "              <h3>Masters Degree under construction!</h3>\n";
echo "            </header>\n";
echo "            </a>\n";
echo "          </article>\n";
echo "        </div>\n";
echo "        <div class=\"4u\">\n";
echo "          <article class=\"item\">\n";
echo "          	<a href=\"https:\/\/github.com/DanielFloripa/BinPackingMultithread-SDI\"  target=\"_blank\" class=\"image fit\"><img src=\"images/threads.png\" alt=\"Threads\" />\n";
echo "            <header>\n";
echo "              <h2>Replication + multithreading </h2>\n";
echo "              <h3>Solve BinPacking problem with multithreading to simulate replication. Java</h3>\n";
echo "            </header>\n";
echo "            </a>\n";
echo "          </article>\n";
echo "        </div>\n";
echo "      </div>\n";
echo "      <div class=\"row\">\n";
echo "        <div class=\"4u\">\n";
echo "          <article class=\"item\">\n";
echo "          	<a href=\"http:\/\/reciclacomigo.com.br\" target=\"_blank\" class=\"image fit\"><img src=\"images/comigo.png\" alt=\"Comigo\"/>\n";
echo "            <header>\n";
echo "              <h2>ReciclaComigo</h2>\n";
echo "              <h3>Reverse Vending Machine. Communication between site (Back+Front on AWS) and the machine computational system.</h3>\n";
echo "            </header>\n";
echo "          	</a>\n";
echo "          </article>\n";
echo "        </div>\n";
echo "        <div class=\"4u\">\n";
echo "          <article class=\"item\">\n";
echo "          	<a href=\"https:\/\/github.com/DanielFloripa/Labp2d\" target=\"_blank\" class=\"image fit\"><img src=\"images/openstack.png\" alt=\"Openstack\"/>\n";
echo "            <header>\n";
echo "              <h2>LabP2D Openstack Scripts</h2>\n";
echo "              <h3>Auto-deploy VMs and measure hosts resources from OpenStack Private Cloud in LabP2D. Bash and Python. </h3>\n";
echo "              </header>\n";
echo "          	</a>\n";
echo "          </article>\n";
echo "        </div>\n";
echo "        <div class=\"4u\">\n";
echo "          <article class=\"item\">\n";
echo "          	<a href=\"https:\/\/github.com/danielfloripa\" target=\"_blank\" class=\"image fit\"><img src=\"images/plus.png\" alt=\"More...\"/>\n";
echo "            <header>\n";
echo "              <h2>Other Projects?</h2>\n";
echo "              <h3>Available on repository </h3>\n";
echo "              </header>\n";
echo "          	</a>\n";
echo "          </article>\n";
echo "        </div>\n";
echo "      </div>\n";
echo "    </div>\n";
echo "  </section>\n";
echo "\n";
echo "    <section id=\"papers\" class=\"three\">\n";
echo "    <div class=\"container\">\n";
echo "    <header>\n";
echo "        <h2>Conference papers</h2>\n";
echo "        <h4>View more in <a href=\"https:\/\/scholar.google.com.br/citations?hl=pt-BR&authuser=1&user=mwcTdEEAAAAJ\" taget=\"_blank\">Google Scholar.</a><br></h4>\n";
echo "    </header>\n";
echo "    <table class=\"default\">\n";
echo "        <thead>\n";
echo "            <tr>\n";
echo "                <th>Title</th>\n";
echo "                <th>File</th>\n";
echo "                <th>Year</th>\n";
echo "                <th>Publisher</th>\n";
echo "            </tr>\n";
echo "        </thead>\n";
echo "        <tbody>\n";
echo "<tr>\n";
echo "<td>Sensoriamento climático em sala de servidores utilizando soluções de software e hardware livre</td>\n";
echo "<td><a href=\"files/publications/2015_Camargo_COTB.pdf\" class=\"icon fa-download\"> </a> </td>\n";
echo "<td rowspan=\"5\"> 2015 </td>\n";
echo "<td> <a href=\"https:\/\/siaiap32.univali.br/seer/index.php/acotb/article/view/7055/3982\" taget=\"_blank\"> COTB </a></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>Automação climática em sala de servidores utilizando hardware livre</td>\n";
echo "<td><a href=\"files/publications/2015_Camargo_ERAD-RS.pdf\" class=\"icon fa-download\"> </a></td>\n";
echo "<td> <a href=\"http:\/\/www.lbd.dcc.ufmg.br/bdbcomp/servlet/Trabalho?id=22831\" taget=\"_blank\"> ERAD-RS </a></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>Monitoramento Ambiental Open Source para Data Center</td>\n";
echo "<td><a href=\"files/publications/2015_Camargo_ERAD-RJ.pdf\" class=\"icon fa-download\"> </a></td>\n";
echo "<td> <a href=\"http:\/\/eradrj2015.lncc.br/forumic/145961.pdf\" taget=\"_blank\"> ERAD-RJ </a></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>Sensoriamento em sala de servidores baseado em software e hardware livres</td>\n";
echo "<td><a href=\"files/publications/2015_Camargo_SIC.pdf\" class=\"icon fa-download\"> </a></td>\n";
echo "<td> <a href=\"http:\/\/www1.udesc.br/arquivos/id_submenu/2551/99.pdf\" taget=\"_blank\"> SIC UDESC </a></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>Automação climática em sala de servidores utilizando hardware livre</td>\n";
echo "<td><a href=\"files/publications/2015_Camargo_Latinoware.pdf\" class=\"icon fa-download\"> </a></td>\n";
echo "<td> <a href=\"http:\/\/latinoware.org/\" taget=\"_blank\"> Latinoware </a></td>\n";
echo "</tr>\n";
echo "        </tbody>\n";
echo "        <tbody>\n";
echo "<tr>\n";
echo "<td>GreenHop: Open source PUE continuous monitoring for small and medium data centers</td>\n";
echo "<td><a href=\"files/publications/2016_Camargo_CLEI.pdf\" class=\"icon fa-download\"> </a></td>\n";
echo "<td rowspan=\"6\"> 2016 </td>\n";
echo "<td> <a href=\"http:\/\/ieeexplore.ieee.org/document/7833381/\" taget=\"_blank\"> IEEE-CLEI </a></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>Automação climática em sala de servidores utilizando hardware livre</td>\n";
echo "<td><a href=\"files/publications/2016_Camargo_ERAD-RS.pdf\" class=\"icon fa-download\"> </a></td>\n";
echo "<td> <a href=\"http:\/\/www.lbd.dcc.ufmg.br/bdbcomp/servlet/Trabalho?id=25002\" taget=\"_blank\"> ERAD-RS </a></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>GreenHop: Environmental and power monitoring small size data centers</td>\n";
echo "<td><a href=\"files/publications/2016_Camargo_CRICTE.pdf\" class=\"icon fa-download\"> </a></td>\n";
echo "<td> <a href=\"http:\/\/cricte.com.br/2016/artigos/CRICTE_2016_paper_94.pdf\" taget=\"_blank\"> CRICTE </a></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>GreenHop: Open source environmental monitoring for small and medium data centers</td>\n";
echo "<td><a href=\"files/publications/2016_Camargo_SCCC.pdf\" class=\"icon fa-download\"> </a></td>\n";
echo "<td> <a href=\"http:\/\/ieeexplore.ieee.org/document/7836064/\" taget=\"_blank\"> IEEE-SCCC </a></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>Sensoriamento em sala de servidores baseado em software e hardware livres</td>\n";
echo "<td><a href=\"files/publications/2016_Camargo_SIC.pdf\" class=\"icon fa-download\"> </a></td>\n";
echo "<td> <a href=\"http:\/\/www1.udesc.br/arquivos/id_submenu/2252/102.pdf\" taget=\"_blank\"> SIC UDESC </a></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>Sensoriamento e automação climática em sala de servidores utilizando software e hardware livre</td>\n";
echo "<td><a href=\"files/publications/2016_TCC_dissertation.pdf\" class=\"icon fa-download\"> </a></td>\n";
echo "<td> <a href=\"http:\/\/pergamumweb.udesc.br/biblioteca/index.php?codAcervo=127333\" taget=\"_blank\"> UDESC dissertation </a></td>\n";
echo "</tr>\n";
echo "        </tbody>\n";
echo "        <tbody>\n";
echo "<tr>\n";
echo "<td>Uma Proposta de Orquestração de Nuvem Computacional Baseada em Consolidação, Elasticidade e Disponibilidade</td>\n";
echo "<td><a href=\"files/publications/2017_Camargo_ERAD-RS.pdf\" class=\"icon fa-download\"> </a></td>\n";
echo "<td rowspan=\"2\"> 2017 </td>\n";
echo "<td> <a href=\"http:\/\/www.lbd.dcc.ufmg.br/bdbcomp/servlet/Trabalho?id=25354\" taget=\"_blank\"> ERAD-RS </a></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>MeHarCEn: A Method of Harmonizing Energy Consumption in Data Centers</td>\n";
echo "<td><a href=\"files/publications/2017_Camargo_RITA.pdf\" class=\"icon fa-download\"> </a></td>\n";
echo "<td> <a href=\"http:\/\/seer.ufrgs.br/index.php/rita/article/view/VOL24-NR2-47\" taget=\"_blank\"> RITA </a></td>\n";
echo "</tr>\n";
echo "</tbody>\n";
echo "\n";
echo "</table>\n";
echo "      <header>\n";
echo "        <h2>Research papers</h2>\n";
echo "      </header>\n";
echo "    <table class=\"default\">\n";
echo "        <thead>\n";
echo "            <tr>\n";
echo "                <th>Title</th>\n";
echo "                <th>File</th>\n";
echo "                <th>Year</th>\n";
echo "                <th>Discipline</th>\n";
echo "            </tr>\n";
echo "        </thead>\n";
echo "    <tbody>\n";
echo "<tr>\n";
echo "<td>Análise envoltória de dados para eficiência energética e termal em processadores de alto desempenho</td>\n";
echo "<td><a href=\"files/works/2016_GS.pdf\" class=\"icon fa-download\"> </a></td>\n";
echo "<td rowspan=\"4\"> 2016 </td>\n";
echo "<td> GS </td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>Internet of Things: Survey About Management Solutions</td>\n";
echo "<td><a href=\"files/works/2016_OGRC.pdf\" class=\"icon fa-download\"> </a></td>\n";
echo "<td> OGRC </td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>Problema Bin Packing com Abordagem Heurística First Fit Decreasing</td>\n";
echo "<td><a href=\"files/works/2016_PAA.pdf\" class=\"icon fa-download\"> </a></td>\n";
echo "<td> PAA </td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>Análise da consolidação de máquinas virtuais nos equipamentos de rede</td>\n";
echo "<td><a href=\"files/works/2016_SDA.pdf\" class=\"icon fa-download\"> </a></td>\n";
echo "<td> SDA </td>\n";
echo "</tr>\n";
echo "    </tbody>\n";
echo "    <tbody>\n";
echo "<tr>\n";
echo "<td>Consolidação de máquinas virtuais com alta disponibilidade: uma revisão bibliográfica sistemática</td>\n";
echo "<td><a href=\"files/works/2017_MEP.pdf\" class=\"icon fa-download\"> </a></td>\n";
echo "<td rowspan=\"4\"> 2017 </td>\n";
echo "<td> MEP </td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>Uma ferramenta para análise do impacto da migraão de máquinas virtuais</td>\n";
echo "<td><a href=\"files/works/2017_REC.pdf\" class=\"icon fa-download\"> </a></td>\n";
echo "<td> REC </td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>CHAVE: Consolidation with High Availability on Virtualized Environments</td>\n";
echo "<td><a href=\"files/works/2017-DEP.pdf\" class=\"icon fa-download\"> </a></td>\n";
echo "<td> DEP </td>\n";
echo "</tr>\n";
echo "<td>Presentation \"CHAVE: Consolidation with High Availability on Virtualized Environments\"</td>\n";
echo "<td><a href=\"files/works/2017_DEP_Presentation.pdf\" class=\"icon fa-download\"> </a></td>\n";
echo "<td> DEP Presentation </td>\n";
echo "</tr>\n";
echo "</tbody>\n";
echo "</table>\n";
echo "<!--for file in `seq 0 ${#LIST[@]}`; do echo -e \"/yyy/ s\/\/${LIST[$file]}/nwq\" | ed links; done-->\n";
echo "    </div>\n";
echo "  </section>\n";
echo "\n";
echo "  <!-- About Me -->\n";
echo "  <section id=\"about\" class=\"two\">\n";
echo "    <div class=\"container\">\n";
echo "      <header>\n";
echo "        <h2>About me</h2>\n";
echo "      </header>\n";
echo "      <a target=\"_blank\" href=\"http:\/\/www.cct.udesc.br\" class=\"icon fa-university\"> UDESC -\n";
echo "      Joinville/SC</a><br>\n";
echo "      <a target=\"_blank\" href=\"http:\/\/lattes.cnpq.br/3806326022567893\" class=\"icon fa-flask\"> Lattes Curriculum</a><br>\n";
echo "      <a target=\"_blank\" href=\"https:\/\/www.linkedin.com/in/daniel13\" class=\"icon fa-linkedin-in\"> Linkedin</a><br>\n";
echo "      <a href=\"http:\/\/api.whatsapp.com/send?phone=5547999675469&text=Contact%20from%20site%20dscamargo.com\" class=\"icon fa-whatsapp\" target=\"_blank\"> Phone: +55 (47) 9 9967-5469</a><br>\n";
echo "      <i class=\"icon fa-envelope\"> daniel at colmeia udesc br</i><br>\n";
echo "      <br>\n";
echo "	 <a href=\"#about\" class=\"image featured\"><img src=\"images/family.jpg\" alt=\"Family\"/></a>\n";
echo "      <div >\n";
echo "      <p style=\"text-align: justify\">\n";
echo "		Casado com a Mariela, pai da princesa Helena, resido em Joinville/SC desde 2011 quando vim para cursar Bacharelado em Ciência da Computação na UDESC/CCT.\n";
echo "        Desde então me apaixonei pela vida acadêmica, sempre participando de atividades de Ensino (obrigatório), Extensão (Grupo Colmeia) e Pesquisa (iniciação científica).\n";
echo "        Continuei a pesquisa no Mestrado em Computação Aplicada pela UDESC, me especializando em Computação em Nuvem, Eficiência Energética, Internet das Coisas (IoT), sistemas críticos, redes, etc.\n";
echo "        Diversos projetos com as linguagens de programação: Python, Shell Script, C, C++, Java, Web (JavaScript, PHP, HTML), além de programação de microcontroladores (ATMEL em C++).\n";
echo "        Venho atuando principalmente em Computação em Nuvem com OpenStack e AWS.\n";
echo "        Adicionalmente, tenho como hobby a cultura \"do it yourself\" (DIY), principalmente Arduino e plataforma ARM, aplicados ao mundo do IoT com monitoramento e automação.\n";
echo "        Possuo forte participação na cultura OpenSource, ministrando palestras e cursos em eventos como Latinoware, FISL, FLISOL, Semana da Computação da UDESC, etc.\n";
echo "        Diversas publicações científicas em eventos como: Escola Regional de Alto Desempenho (ERAD) (RS, RJ e SP) desde 2014, IEEE/CLEI, IEEE/SCCC, dentre outros.\n";
echo "        Interesse nos temas: Cloud Computing, Critical Systems, Internet of Things (IoT), Smart Cities, Green IT e Artificial Intelligence.\n";
echo "        Há dois projetos pesquisa em andamento no Laboratório de Processamento Paralelo e Distribuído (LabP2D) da UDESC-Joinville.\n";
echo "        Consequência da graduação, o <em>\"GreenHop: Sensoriamento e automação de Data Centers\"</em> e do mestrado <em>\"CHAVE: Consolidation and High Availability on Virtual Environments\"</em>.\n";
echo "        Ex-membro do conselho diretivo do <a target=\"_blank\" href=\"http:\/\/www.fablabjoinville.com.br\" > Fab-Lab Joinville-SC</a>, com cursos e palestras ministrados para a comunidade de Joinville e região, disseminando o acesso à tecnologia e inovação voltados à Cultura Maker.\n";
echo "        Como experiências profissionais, fui colaborador da Startup Comigo, vencedora do prêmio do Sinapse da Inovação em 2016 com a proposta de uma máquina de logística reversa de latas e garrafas PET,\n";
echo "        sendo responsável pelo desenvolvimento do hardware computacional da máquina, de parte do <a target=\"_blank\" href=\"http:\/\/www.reciclacomigo.com.br\" >site</a> e de toda a infraestrutura virtual hospedada na Amazon Web Services.\n";
echo "      </div>\n";
echo "    </div>\n";
echo "  </section>\n";
echo "  <!-- Contact -->\n";
echo "  <section id=\"contact\" class=\"four\">\n";
echo "    <div class=\"container\">\n";
echo "      <header>\n";
echo "        <h2>Contact</h2>\n";
echo "      </header>\n";
echo "      <form method=\"POST\" action=\"https:\/\/formspree.io/daniel.camargo@hotmail.com\" >\n";
echo "        <div class=\"row half\">\n";
echo "          <div class=\"6u\">\n";
echo "            <input type=\"text\" name=\"name\" placeholder=\"Your name\"/>\n";
echo "          </div>\n";
echo "          <div class=\"6u\">\n";
echo "            <input type=\"email\" name=\"email\" placeholder=\"Your e-mail\"/>\n";
echo "          </div>\n";
echo "          <input type=\"hidden\" name=\"_subject\" value=\"From site: danielfloripa.io index\"/>\n";
echo "        </div>\n";
echo "        <div class=\"row half\">\n";
echo "          <div class=\"12u\">\n";
echo "            <textarea name=\"message\" placeholder=\"Your message\">
echo "          </div>\n";
echo "        </div>\n";
echo "        <div class=\"row\">\n";
echo "          <div class=\"12u\">\n";
echo "            <input type=\"submit\" value=\"Send Message!\"/>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "        <input type=\"hidden\" name=\"_next\" value=\"thanks.php\" />\n";
echo "      </form>\n";
echo "    </div>\n";
echo "  </section>\n";
echo "</div>\n";
echo "<!-- Footer -->\n";
echo "<div id=\"footer\"> <!--#include file=\"footer.html\" --> </div>\n";
echo "</body>\n";
echo "</html>";
?>
