<?php

echo "<!DOCTYPE HTML>\n";
echo "<html> <!-- class=\"loading\"-->\n";
echo "<head>\n";
echo "    <title>Curriculum Vittae :: Daniel Scheidemantel Camargo</title>\n";
echo "    <meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\"/>\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
echo "    <meta name=\"description\" content=\"Curriculum Daniel Scheidemantel Camargo\"/>\n";
echo "    <meta name=\"keywords\" content=\"Curriculum; Daniel; Scheidemantel; Camargo\"/>\n";
echo "    <meta name=\"referrer\" content=\"origin\">\n";
echo "    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"ico/apple-icon-57x57.png\">\n";
echo "    <link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"ico/apple-icon-60x60.png\">\n";
echo "    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"ico/apple-icon-72x72.png\">\n";
echo "    <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"ico/apple-icon-76x76.png\">\n";
echo "    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"ico/apple-icon-114x114.png\">\n";
echo "    <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"ico/apple-icon-120x120.png\">\n";
echo "    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"ico/apple-icon-144x144.png\">\n";
echo "    <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"ico/apple-icon-152x152.png\">\n";
echo "    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"ico/apple-icon-180x180.png\">\n";
echo "    <!--[if IE]><link rel=\"shortcut icon\" href=\"ico/favicon.ico\"><![endif]-->\n";
echo "    <link rel=\"icon\" type=\"image/png\" sizes=\"192x192\"  href=\"ico/android-icon-192x192.png\">\n";
echo "    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"ico/favicon-32x32.png\">\n";
echo "    <link rel=\"icon\" type=\"image/png\" sizes=\"96x96\" href=\"ico/favicon-96x96.png\">\n";
echo "    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"ico/favicon-16x16.png\">\n";
echo "    <link rel=\"manifest\" href=\"/manifest.json\">\n";
echo "    <meta name=\"msapplication-TileColor\" content=\"#ffffff\">\n";
echo "    <meta name=\"msapplication-TileImage\" content=\"ico/ms-icon-144x144.png\">\n";
echo "    <meta name=\"theme-color\" content=\"#ffffff\">\n";
echo "\n";
echo "    <script src=\"js/jquery.min.js\"></script>\n";
echo "    <script src=\"js/jquery.scrolly.min.js\"></script>\n";
echo "    <script src=\"js/jquery.scrollzer.min.js\"></script>\n";
echo "    <script src=\"js/skel.min.js\"></script>\n";
echo "    <script src=\"js/skel-layers.min.js\"></script>\n";
echo "    <script src=\"js/init.js\"></script>\n";
echo "    <script src=\"//code.jquery.com/jquery-1.10.2.js\"></script>\n";
echo "    <script>\n";
echo "        $(function(){\n";
echo "            $(\"#footer\").load(\"footer.html\");\n";
echo "        });\n";
echo "    </script>\n";
echo "</head>\n";
echo "<body>\n";
echo "\n";
echo "<!-- Header -->\n";
echo "<div id=\"header\" class=\"skel-layers-fixed entry-header\">\n";
echo "\n";
echo "    <div id=\"loader-wrapper\">\n";
echo "        <div id=\"loader\"></div>\n";
echo "        <div class=\"loader-section section-left\"></div>\n";
echo "        <div class=\"loader-section section-right\"></div>\n";
echo "    </div>\n";
echo "\n";
echo "    <div class=\"top\">\n";
echo "        <header>\n";
echo "            <h1 class=\"entry-title\">Curriculum Vittae</h1>\n";
echo "        </header>\n";
echo "        <!-- Logo -->\n";
echo "        <div id=\"logo\">\n";
echo "            <a href=\"#top\" class=\"image avatar48\"><img src=\"images/me.jpg\"/></a><br>\n";
echo "        </div>\n";
echo "        <!-- Nav -->\n";
echo "        <nav id=\"nav\">\n";
echo "            <ul>\n";
echo "                <li>\n";
echo "                    <a href=\"http://danielfloripa.github.io\" id=\"return\" class=\"skel-layers-ignoreHref\"><span class=\"icon fa-home\">Back to home</span></a>\n";
echo "                </li>\n";
echo "            </ul>\n";
echo "        </nav>\n";
echo "    </div>\n";
echo "\n";
echo "\n";
echo "\n";
echo "</div>\n";
echo "\n";
echo "<!-- Main -->\n";
echo "<div id=\"main\">\n";
echo "\n";
echo "\n";
echo "    <!-- Personal -->\n";
echo "    <section id=\"top\" class=\"two cover\">\n";
echo "\n";
echo "        <div class=\"container\">\n";
echo "            <header>\n";
echo "                <h2>Thank you for your message!</h2>\n";
echo "                <h3>I will contact you soon.</h3>\n";
echo "\n";
echo "\n";
echo "            </header>\n";
echo "        </div>\n";
echo "    </section>\n";
echo "\n";
echo "\n";
echo "</div>\n";
echo "\n";
echo "<!-- Footer -->\n";
echo "<div id=\"footer\"> <!--#include file=\"footer.html\" --> </div>\n";
echo "\n";
echo "</body>\n";
echo "</html>";
?>
